name: CrossMix-OS Release

permissions:
  id-token: "write"
  contents: "write"
  packages: "write"
  pull-requests: "read"

on:
  workflow_dispatch:

jobs:
  tagged-release:
    name: Tagged release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        run: |
          TAG="${{ github.ref_name }}"
          echo "BUILD_VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Install 7-Zip 24.06
        run: |
          mkdir -p /root/tools
          wget https://www.7-zip.org/a/7z2406-linux-x64.tar.xz -P /root/tools
          tar xvf /root/tools/7z2406-linux-x64.tar.xz -C /root/workspace/test/tools
          mv /root/workspace/test/tools/7zz /usr/local/bin/7zz

      - name: Extract RetroArch cores
        run: |
          find /root/workspace/RetroArch/.retroarch/cores -name "*.7z" -execdir 7zz x {} \; -execdir rm {} \;

      - name: Cleaning image...
        run: |
          find ./CrossMix-OS -type f -name ".gitkeep" -delete
          rm -rf /root/workspace/_assets
          rm /root/workspace/LICENSE
          rm /root/workspace/README.md
          ls -la ./CrossMix-OS
          rm -rf /root/workspace/.git
          rm -rf /root/workspace/.github
          ls -la ./CrossMix-OS

      - name: Install 7-Zip
        run: sudo apt-get update && sudo apt-get install p7zip-full

      - name: 7zipping release
        run: |
          7zz a "CrossMix-OS_v${{ env.BUILD_VERSION }}.7z" /root/workspace/.

      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: "CrossMix-OS v${{ env.BUILD_VERSION }}"
          prerelease: false
          files: "CrossMix-OS_v${{ env.BUILD_VERSION }}.7z"
          draft: false
